spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: music-service-route
          uri: lb://music-service
          predicates:
            - Path=/music/**
        - id: music-library-service-route
          uri: lb://music-library-service
          predicates:
            - Path=/playlist/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
